---
title: "Mini Project 2"
author: "Audrey Bertin and Eva Gerstle"
date: "10/23/2017"
output: html_document
---


### Loading The Data

```{r, message = FALSE, warning = FALSE}
library(tidyverse)

load("committees.rda")
load("contributions.rda")
load("individuals.rda")
```

### Join committees and individual donations to get a list of all donations to each committee
```{r}

selected_individuals <- individuals %>%
  select(occupation, transaction_amt)

donations_to_committees <- committees %>% 
  select(cmte_id, cmte_name, cmte_party_affiliation) %>%
  inner_join(individuals, by = "cmte_id") 
```

### Select some jobs to consider for studying

```{r}

jobs <- c("REGISTERED NURSE", "TEACHER", "SOCIAL WORKER", "FARMER", "CONSTRUCTION", "RANCHER", "REAL ESTATE", "ACCOUNTANT", "SOFTWARE ENGINEER", "MARKETING", "CONSULTANT", "CONTRACTOR", "CEO", "LAWYER", "EXECUTIVE", "PRESIDENT", "DOCTOR", "ANESTHESIOLOGIST")

```

### Calculate the size of donations for each of these occupations

```{r}

occupation_donations <- function(job) {
  donations_to_committees %>%
  filter(occupation == job) %>%
  group_by(occupation) %>%
  summarize(total_donated = sum(transaction_amt), avg_donated = mean(transaction_amt), median_donation = median(transaction_amt), num_donations = n()) }

donations_by_occupations <- lapply(jobs, FUN = occupation_donations) %>% bind_rows()

donations_by_occupations <- mutate(donations_by_occupations, total_donated_millions = total_donated/1000000)

low_income = c("REGISTERED NURSE", "TEACHER", "SOCIAL WORKER", "FARMER", "CONSTRUCTION", "RANCHER")
med_income = c( "REAL ESTATE", "ACCOUNTANT", "SOFTWARE ENGINEER", "MARKETING", "CONSULTANT", "CONTRACTOR")
high_income = c("CEO", "LAWYER", "EXECUTIVE", "PRESIDENT", "DOCTOR", "ANESTHESIOLOGIST")

donations_by_occupations <- donations_by_occupations %>% 
  mutate(income_level = ifelse(occupation %in% low_income, "$20K-60K", ifelse(occupation %in% med_income, "$60k-100k", "$100K +")))

donations_by_occupations$income_level <- factor(donations_by_occupations$income_level, levels = c("$20K-60K", "$60k-100k", "$100K +"))


```



#Plot the total sum of donations given by each of the 18 occupations. 
```{r}

total_plot <- ggplot(donations_by_occupations, aes(x= reorder(occupation,total_donated_millions), y=total_donated_millions, fill= income_level)) + geom_bar(stat = "identity") +
theme(axis.text.x = element_text(angle = 90, size = 7, hjust = 1)) + xlab(NULL) +
ylab("Total Donations (In Millions Of Dollars)") + scale_fill_discrete(name= "Income Level", breaks = c("$20K-60K", "$60k-100k", "$100K +"), labels = c("$20K-60K", "$60k-100k", "$100K +")) + ggtitle("Total Donations by Occupation")

total_plot


```


### Plot median donations by occupation

```{r}

median_plot <- ggplot(donations_by_occupations, aes(x=reorder(occupation,total_donated_millions), y = median_donation, fill = income_level)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1) ) + scale_fill_discrete(name= "Income Level", breaks = c("$20K-60K", "$60k-100k", "$100K +"), labels = c("$20K-60K", "$60k-100k", "$100K +")) +
  xlab(NULL) +
  ylab("Median Donation (Dollars)")+
  ggtitle("Median Individual Contributions by Occupation")

median_plot

```


### Find the partisanship by occupation
```{r}

committees_by_occupation <- function(job) {
  donations_to_committees %>%
  filter(occupation == job) %>%
  group_by(occupation, cmte_name, cmte_id, cmte_party_affiliation) %>%
  summarize(total_donations = sum(transaction_amt), num_donations = n()) %>%
  arrange(desc(total_donations))

}

all_committees_by_occupation <- lapply(jobs, FUN = committees_by_occupation) %>% bind_rows()
all_committees_by_occupation 

occupation_partisanship <- all_committees_by_occupation %>%
  group_by(occupation) %>%
  summarize(num_democratic = sum(cmte_party_affiliation == "DEM"), num_republican = sum(cmte_party_affiliation == "REP"), favor = ifelse(num_democratic > num_republican, "Dem", "Rep"))


occupations_with_partisanship <- donations_by_occupations %>%
  inner_join(occupation_partisanship, by = "occupation") 

partisanship_gathered <- occupations_with_partisanship %>%
  select(-favor) %>%
  rename(D = num_democratic, R = num_republican) %>%
  gather(key = "party", value = "num_committees", D:R)
  
partisanship_gathered$party <- factor(partisanship_gathered$party, levels = c("D", "R"))  
  

```


```{r}

ggplot(partisanship_gathered, aes(x = occupation, y = num_committees, fill = party)) +
  geom_bar(stat = "identity", position = "Fill") +
  facet_wrap(~income_level, scales = "free_x") +
  xlab(NULL) +
  ylab("Percentage of Committees Supported")  +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  ggtitle("Individual Donations by Income Level and Occupation") +
  scale_fill_manual(values = c("Blue", "Red"),name= "Committee Affiliation", breaks = c("D","R"), labels = c("Democratic", "Republican"))

```
  





